import mongoose from "mongoose";
import slugify from "slugify";

const projectSchema = new mongoose.Schema({
    name: { type: String, required: true },
    slug: { type: String, unique: true },

    location: {
        city: { type: String, required: true },
        division: { type: String },
    },

    startDate: { type: Date, required: true },
    endDate: { type: Date },
    description: { type: String, required: true },

    tags: [{ type: String, required: true }],

    thumbnailURL: { type: String, required: true },
    bannerURL: { type: String, required: true },
    gallerySpreadsheetURL: { type: String, required: true },
    financialRecordURL: { type: String, required: true },

    impact: {
        peopleServed: { type: Number, default: 0 },
        volunteersEngaged: { type: Number, default: 0 },
        materialsDistributed: { type: Number, default: 0 }
    },

    volunteers: [{
        // id automatically generated by mongoDB
        volunteerUserID: { type: String, unique: true, required: true },
        volunteerEmail: { type: String, unique: true, lowercase: true, trim: true, required: true },
        volunteeringHours: { type: Number, default: 0 },
        certificateURL: { type: String },
        impactDescription: { type: String }
    }],

    collaborators: [{
        name: { type: String, required: true },
        logoURL: { type: String },
        website: { type: String }
    }],

    sponsors: [{
        name: { type: String, required: true },
        logoURL: { type: String },
        website: { type: String }
    }],

    status: {
        type: String,
        enum: ['Upcoming', 'Ongoing', 'Completed'],
        default: 'Upcoming'
    },

    isPublic: { type: Boolean, default: true }
}, { timestamps: true });

projectSchema.pre('save', function (next) {
    if (!this.slug) {
        this.slug = slugify(this.name, { lower: true, strict: true });
    }
    next();
});

const Project = mongoose.models.Project || mongoose.model("Project", projectSchema);
export default Project;
